# openldap, phpLDAPadmin, pwm
version: '2'
services:
  ldap:
    image: osixia/openldap:1.2.0
    hostname: ldap
    volumes:
      - /home/docker/openldap/data:/var/lib/ldap
      - /home/docker/openldap/etc:/etc/ldap/slapd.d
    restart: always
    environment:
      - LDAP_ORGANISATION=example
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=passw0rd
  phpldpaadmin:
    image: osixia/phpldapadmin:0.7.1
    links:
      - ldap:ldap-host
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
  pwm:
    image: fjudith/pwm:latest
    ports:
      - "8080:8080"
    volumes:
      - /home/docker/pwm:/usr/share/pwm
